### PR TITLE
Minor changes for ST3

### PR DESCRIPTION
**Pull request by paultyng**
Got it to format in ST3, mostly the StringIO changes are what affected it.  Should probably be refactored but just needed to get the formatting working.

### CODE REVIEW

**Comment by waynemoore** [comment]
@paultyng thanks for the contribution!

I'm holding off on merging at this point because the tests are broken.  So I need to see how feasible it is to have a test suite that works across ST2 and ST3.  I guess it's about time I install ST3 :wink:

**Comment by paultyng** [comment]
Ah ok, I'll see if I can take a look as well, didn't use the tests just got it running without error in ST3.

**Comment by waynemoore** [comment]
Haven't forgotten about this, limited time and trying to find a way to make this work across Python 2.x and 3.x as cleanly as I can :v:

**Comment by waynemoore** [comment]
@paultyng merged in.  Had to refactor a bit to get it to work with Python 2/3 & ST2/3.  Going to submit to Sublime Package Control to get them to allow installing on ST3.  I would appreciate if you could give the latest version a test for me.

Thanks for your contribution :v:

**Pull request merged**
